version: '3.8'

services:
  container_1:
    environment:
      - ID=0
      - PORT=5000
    ports:
      - "5000:5000"
    build: .
    volumes:
      - ./shared_data:/shared

  container_2:
    environment:
      - ID=1
      - PORT=5001
    ports:
      - "5001:5001"
    build: .
    volumes:
      - ./shared_data:/shared

  container_3:
    environment:
      - ID=2
      - PORT=5002
    ports:
      - "5002:5002"
    build: .
    volumes:
      - ./shared_data:/shared

  container_4:
    environment:
      - ID=3
      - PORT=5003
    ports:
      - "5003:5003"
    build: .
    volumes:
      - ./shared_data:/shared

  container_5:
    environment:
      - ID=4
      - PORT=5004
    ports:
      - "5004:5004"
    build: .
    volumes:
      - ./shared_data:/shared
